# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    include:
      - "*"
  paths:
    include:
    - rootfs/
    - Dockerfile
    - build.json
    - go.mod
    - main.go
    - http.go
    - supervisor.go
pr: none
variables:
  - name: versionBuilder
    value: "7.2.0"
  - group: docker
  - group: github
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

stages:

  - stage: "Build"
    jobs:
      - job: "ReleaseDocker"
        timeoutInMinutes: 240
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          maxParallel: 5
          matrix:
            amd64:
              buildArch: "amd64"
            i386:
              buildArch: "i386"
            armhf:
              buildArch: "armhf"
            armv7:
              buildArch: "armv7"
            aarch64:
              buildArch: "aarch64"
        steps:
          - template: templates/azp-step-plugin-version.yaml@azure
          - script: |
              docker login -u $(dockerUser) -p $(dockerPassword)
            displayName: "Docker hub login"
          - script: docker pull homeassistant/amd64-builder:$(versionBuilder)
            displayName: "Install Builder"
          - script: |
              sudo docker run --rm --privileged \
                  -v ~/.docker:/root/.docker \
                  -v /run/docker.sock:/run/docker.sock:rw \
                  -v $(pwd):/data:ro \
                  homeassistant/amd64-builder:$(versionBuilder) \
                    --generic $(pluginRelease) "--$(buildArch)" -t /data
            displayName: "Build Release"

  - stage: "Publish"
    jobs:
      - job: "ReleaseHassio"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: templates/azp-step-plugin-version.yaml@azure
          - script: |
              sudo apt-get install -y --no-install-recommends \
                git jq curl

              git config --global user.name "Pascal Vizeli"
              git config --global user.email "pvizeli@syshack.ch"
              git config --global credential.helper store

              echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
          - script: |
              set -e

              version="$(pluginRelease)"

              git clone https://github.com/home-assistant/hassio-version
              cd hassio-version

              dev_version="$(jq --raw-output '.observer' dev.json)"
              beta_version="$(jq --raw-output '.observer' beta.json)"

              if [[ "$version" =~ dev ]]; then
                sed -i "s|\"observer\": \"$dev_version\"|\"observer\": \"$version\"|g" dev.json
              else
                sed -i "s|\"observer\": \"$beta_version\"|\"observer\": \"$version\"|g" beta.json
              fi

              git commit -am "Bump Observer $version"
              git push
            displayName: "Update version files"
